import { Listing } from "./Listing.interface";
export const initialListings: Listing[] = [
  // ─── Cal Poly SLO ───────────────────────────────────────────
  {
    id: 1,
    campus: "Cal Poly SLO",
    address: "123 Foothill Blvd",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93405",
    distanceToCampus: 0.4,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFootage: 850,
    rentPerMonth: 1800,
    depositAmount: 1800,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Mark Rivera",
    contactEmail: "mark.rivera@email.com",
    contactPhone: "805-555-0101",
    listedAt: "2025-06-01",
    updatedAt: "2025-06-01",
    postedBy: "agent",
  },
  {
    id: 2,
    campus: "Cal Poly SLO",
    address: "456 California Blvd",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93405",
    distanceToCampus: 0.7,
    type: "house",
    bedrooms: 4,
    bathrooms: 2,
    squareFootage: 1600,
    rentPerMonth: 3800,
    depositAmount: 3800,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Susan Park",
    contactEmail: "susan.park@email.com",
    contactPhone: "805-555-0102",
    listedAt: "2025-06-03",
    updatedAt: "2025-06-03",
    postedBy: "agent",
  },
  {
    id: 3,
    campus: "Cal Poly SLO",
    address: "789 Monterey St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93401",
    distanceToCampus: 1.2,
    type: "studio",
    bedrooms: 0,
    bathrooms: 1,
    squareFootage: 420,
    rentPerMonth: 1300,
    depositAmount: 1300,
    utilitiesIncluded: true,
    availableFrom: "2025-08-15",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Tom Nguyen",
    contactEmail: "tom.nguyen@email.com",
    contactPhone: "805-555-0103",
    listedAt: "2025-06-05",
    updatedAt: "2025-06-05",
    postedBy: "agent",
  },
  {
    id: 4,
    campus: "Cal Poly SLO",
    address: "321 Grand Ave",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93405",
    distanceToCampus: 0.9,
    type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 600,
    rentPerMonth: 1500,
    depositAmount: 1500,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: true,
      gym: true,
      pool: true,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Linda Cho",
    contactEmail: "linda.cho@email.com",
    contactPhone: "805-555-0104",
    listedAt: "2025-06-07",
    updatedAt: "2025-06-07",
    postedBy: "agent",
  },
  {
    id: 5,
    campus: "Cal Poly SLO",
    address: "654 Higuera St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93401",
    distanceToCampus: 1.5,
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 200,
    rentPerMonth: 900,
    depositAmount: 900,
    utilitiesIncluded: true,
    availableFrom: "2025-08-01",
    leaseDuration: 9,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "James Wu",
    contactEmail: "james.wu@email.com",
    contactPhone: "805-555-0105",
    listedAt: "2025-06-08",
    updatedAt: "2025-06-08",
    postedBy: "student",
  },
  {
    id: 6,
    campus: "Cal Poly SLO",
    address: "111 Slack St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93405",
    distanceToCampus: 0.5,
    type: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1100,
    rentPerMonth: 2800,
    depositAmount: 2800,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Amy Torres",
    contactEmail: "amy.torres@email.com",
    contactPhone: "805-555-0106",
    listedAt: "2025-06-09",
    updatedAt: "2025-06-09",
    postedBy: "agent",
  },
  {
    id: 7,
    campus: "Cal Poly SLO",
    address: "200 Taft St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93405",
    distanceToCampus: 1.0,
    type: "house",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1400,
    rentPerMonth: 3200,
    depositAmount: 3200,
    utilitiesIncluded: false,
    availableFrom: "2025-09-15",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: false,
      gym: false,
      pool: true,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Greg Hall",
    contactEmail: "greg.hall@email.com",
    contactPhone: "805-555-0107",
    listedAt: "2025-06-10",
    updatedAt: "2025-06-10",
    postedBy: "agent",
  },
  {
    id: 8,
    campus: "Cal Poly SLO",
    address: "88 Breck St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93405",
    distanceToCampus: 0.6,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 950,
    rentPerMonth: 2200,
    depositAmount: 2200,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Nina Patel",
    contactEmail: "nina.patel@email.com",
    contactPhone: "805-555-0108",
    listedAt: "2025-06-11",
    updatedAt: "2025-06-11",
    postedBy: "agent",
  },
  {
    id: 9,
    campus: "Cal Poly SLO",
    address: "400 Murray Ave",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93405",
    distanceToCampus: 1.3,
    type: "condo",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1050,
    rentPerMonth: 2400,
    depositAmount: 2400,
    utilitiesIncluded: false,
    availableFrom: "2025-08-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: true,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Carlos Vega",
    contactEmail: "carlos.vega@email.com",
    contactPhone: "805-555-0109",
    listedAt: "2025-06-12",
    updatedAt: "2025-06-12",
    postedBy: "agent",
  },
  {
    id: 10,
    campus: "Cal Poly SLO",
    address: "77 Johnson Ave",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93401",
    distanceToCampus: 2.0,
    type: "house",
    bedrooms: 5,
    bathrooms: 3,
    squareFootage: 2200,
    rentPerMonth: 5000,
    depositAmount: 5000,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: false,
      pool: true,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Rachel Kim",
    contactEmail: "rachel.kim@email.com",
    contactPhone: "805-555-0110",
    listedAt: "2025-06-13",
    updatedAt: "2025-06-13",
    postedBy: "agent",
  },
  {
    id: 11,
    campus: "Cal Poly SLO",
    address: "33 Chorro St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93401",
    distanceToCampus: 1.1,
    type: "studio",
    bedrooms: 0,
    bathrooms: 1,
    squareFootage: 380,
    rentPerMonth: 1150,
    depositAmount: 1150,
    utilitiesIncluded: true,
    availableFrom: "2025-07-15",
    leaseDuration: 6,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Derek Lam",
    contactEmail: "derek.lam@email.com",
    contactPhone: "805-555-0111",
    listedAt: "2025-06-14",
    updatedAt: "2025-06-14",
    postedBy: "student",
  },
  {
    id: 12,
    campus: "Cal Poly SLO",
    address: "500 Santa Rosa St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93401",
    distanceToCampus: 0.8,
    type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 650,
    rentPerMonth: 1600,
    depositAmount: 1600,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Mia Johnson",
    contactEmail: "mia.johnson@email.com",
    contactPhone: "805-555-0112",
    listedAt: "2025-06-15",
    updatedAt: "2025-06-15",
    postedBy: "agent",
  },
  {
    id: 13,
    campus: "Cal Poly SLO",
    address: "210 Broad St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93401",
    distanceToCampus: 1.8,
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 180,
    rentPerMonth: 800,
    depositAmount: 800,
    utilitiesIncluded: true,
    availableFrom: "2025-08-01",
    leaseDuration: 9,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Sam Ortiz",
    contactEmail: "sam.ortiz@email.com",
    contactPhone: "805-555-0113",
    listedAt: "2025-06-16",
    updatedAt: "2025-06-16",
    postedBy: "student",
  },
  {
    id: 14,
    campus: "Cal Poly SLO",
    address: "750 Islay St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93401",
    distanceToCampus: 1.4,
    type: "condo",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1300,
    rentPerMonth: 3000,
    depositAmount: 3000,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Fiona Chang",
    contactEmail: "fiona.chang@email.com",
    contactPhone: "805-555-0114",
    listedAt: "2025-06-17",
    updatedAt: "2025-06-17",
    postedBy: "agent",
  },
  {
    id: 15,
    campus: "Cal Poly SLO",
    address: "99 Nipomo St",
    city: "San Luis Obispo",
    state: "CA",
    zipCode: "93401",
    distanceToCampus: 0.3,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFootage: 780,
    rentPerMonth: 1950,
    depositAmount: 1950,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Owen Brooks",
    contactEmail: "owen.brooks@email.com",
    contactPhone: "805-555-0115",
    listedAt: "2025-06-18",
    updatedAt: "2025-06-18",
    postedBy: "agent",
  },

  // ─── UCLA ────────────────────────────────────────────────────
  {
    id: 16,
    campus: "UCLA",
    address: "101 Gayley Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.3,
    type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 550,
    rentPerMonth: 2200,
    depositAmount: 2200,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Priya Nair",
    contactEmail: "priya.nair@email.com",
    contactPhone: "310-555-0201",
    listedAt: "2025-06-01",
    updatedAt: "2025-06-01",
    postedBy: "agent",
  },
  {
    id: 17,
    campus: "UCLA",
    address: "305 Landfair Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.5,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFootage: 800,
    rentPerMonth: 3200,
    depositAmount: 3200,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Jake Morrow",
    contactEmail: "jake.morrow@email.com",
    contactPhone: "310-555-0202",
    listedAt: "2025-06-02",
    updatedAt: "2025-06-02",
    postedBy: "agent",
  },
  {
    id: 18,
    campus: "UCLA",
    address: "440 Strathmore Dr",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.7,
    type: "studio",
    bedrooms: 0,
    bathrooms: 1,
    squareFootage: 400,
    rentPerMonth: 1800,
    depositAmount: 1800,
    utilitiesIncluded: true,
    availableFrom: "2025-08-15",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Ella Morris",
    contactEmail: "ella.morris@email.com",
    contactPhone: "310-555-0203",
    listedAt: "2025-06-03",
    updatedAt: "2025-06-03",
    postedBy: "agent",
  },
  {
    id: 19,
    campus: "UCLA",
    address: "812 Kelton Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.4,
    type: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1100,
    rentPerMonth: 4500,
    depositAmount: 4500,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Brian Lee",
    contactEmail: "brian.lee@email.com",
    contactPhone: "310-555-0204",
    listedAt: "2025-06-04",
    updatedAt: "2025-06-04",
    postedBy: "agent",
  },
  {
    id: 20,
    campus: "UCLA",
    address: "600 Levering Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.6,
    type: "house",
    bedrooms: 4,
    bathrooms: 2,
    squareFootage: 1700,
    rentPerMonth: 6500,
    depositAmount: 6500,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: false,
      pool: true,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Diana Fox",
    contactEmail: "diana.fox@email.com",
    contactPhone: "310-555-0205",
    listedAt: "2025-06-05",
    updatedAt: "2025-06-05",
    postedBy: "agent",
  },
  {
    id: 21,
    campus: "UCLA",
    address: "220 Midvale Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.9,
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 200,
    rentPerMonth: 1200,
    depositAmount: 1200,
    utilitiesIncluded: true,
    availableFrom: "2025-08-01",
    leaseDuration: 9,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Kevin Tran",
    contactEmail: "kevin.tran@email.com",
    contactPhone: "310-555-0206",
    listedAt: "2025-06-06",
    updatedAt: "2025-06-06",
    postedBy: "student",
  },
  {
    id: 22,
    campus: "UCLA",
    address: "715 Veteran Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 1.1,
    type: "condo",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1000,
    rentPerMonth: 3800,
    depositAmount: 3800,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: true,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Sophie Adams",
    contactEmail: "sophie.adams@email.com",
    contactPhone: "310-555-0207",
    listedAt: "2025-06-07",
    updatedAt: "2025-06-07",
    postedBy: "agent",
  },
  {
    id: 23,
    campus: "UCLA",
    address: "380 Hilgard Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.2,
    type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 500,
    rentPerMonth: 2400,
    depositAmount: 2400,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Liam Stone",
    contactEmail: "liam.stone@email.com",
    contactPhone: "310-555-0208",
    listedAt: "2025-06-08",
    updatedAt: "2025-06-08",
    postedBy: "agent",
  },
  {
    id: 24,
    campus: "UCLA",
    address: "555 Ophir Dr",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 1.3,
    type: "house",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1500,
    rentPerMonth: 5500,
    depositAmount: 5500,
    utilitiesIncluded: false,
    availableFrom: "2025-09-15",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Natalie Cruz",
    contactEmail: "natalie.cruz@email.com",
    contactPhone: "310-555-0209",
    listedAt: "2025-06-09",
    updatedAt: "2025-06-09",
    postedBy: "agent",
  },
  {
    id: 25,
    campus: "UCLA",
    address: "900 Westwood Blvd",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.8,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFootage: 750,
    rentPerMonth: 3000,
    depositAmount: 3000,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: true,
      gym: true,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Tyler Ross",
    contactEmail: "tyler.ross@email.com",
    contactPhone: "310-555-0210",
    listedAt: "2025-06-10",
    updatedAt: "2025-06-10",
    postedBy: "agent",
  },
  {
    id: 26,
    campus: "UCLA",
    address: "142 Warner Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 1.6,
    type: "studio",
    bedrooms: 0,
    bathrooms: 1,
    squareFootage: 360,
    rentPerMonth: 1700,
    depositAmount: 1700,
    utilitiesIncluded: true,
    availableFrom: "2025-07-01",
    leaseDuration: 6,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Zoe Bennett",
    contactEmail: "zoe.bennett@email.com",
    contactPhone: "310-555-0211",
    listedAt: "2025-06-11",
    updatedAt: "2025-06-11",
    postedBy: "student",
  },
  {
    id: 27,
    campus: "UCLA",
    address: "460 Roebling Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 1.0,
    type: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1200,
    rentPerMonth: 4800,
    depositAmount: 4800,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: true,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Marcus Webb",
    contactEmail: "marcus.webb@email.com",
    contactPhone: "310-555-0212",
    listedAt: "2025-06-12",
    updatedAt: "2025-06-12",
    postedBy: "agent",
  },
  {
    id: 28,
    campus: "UCLA",
    address: "33 Glenrock Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.4,
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 190,
    rentPerMonth: 1100,
    depositAmount: 1100,
    utilitiesIncluded: true,
    availableFrom: "2025-08-01",
    leaseDuration: 9,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Aisha Grant",
    contactEmail: "aisha.grant@email.com",
    contactPhone: "310-555-0213",
    listedAt: "2025-06-13",
    updatedAt: "2025-06-13",
    postedBy: "student",
  },
  {
    id: 29,
    campus: "UCLA",
    address: "850 Weyburn Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.6,
    type: "condo",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 980,
    rentPerMonth: 4000,
    depositAmount: 4000,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Ryan Cole",
    contactEmail: "ryan.cole@email.com",
    contactPhone: "310-555-0214",
    listedAt: "2025-06-14",
    updatedAt: "2025-06-14",
    postedBy: "agent",
  },
  {
    id: 30,
    campus: "UCLA",
    address: "210 Broxton Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90024",
    distanceToCampus: 0.5,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 900,
    rentPerMonth: 3500,
    depositAmount: 3500,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Hannah Mills",
    contactEmail: "hannah.mills@email.com",
    contactPhone: "310-555-0215",
    listedAt: "2025-06-15",
    updatedAt: "2025-06-15",
    postedBy: "agent",
  },

  // ─── UC Berkeley ─────────────────────────────────────────────
  {
    id: 31,
    campus: "UC Berkeley",
    address: "2400 Telegraph Ave",
    city: "Berkeley",
    state: "CA",
    zipCode: "94704",
    distanceToCampus: 0.3,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFootage: 780,
    rentPerMonth: 2800,
    depositAmount: 2800,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Leo Nakamura",
    contactEmail: "leo.nakamura@email.com",
    contactPhone: "510-555-0301",
    listedAt: "2025-06-01",
    updatedAt: "2025-06-01",
    postedBy: "agent",
  },
  {
    id: 32,
    campus: "UC Berkeley",
    address: "1850 Haste St",
    city: "Berkeley",
    state: "CA",
    zipCode: "94709",
    distanceToCampus: 0.5,
    type: "studio",
    bedrooms: 0,
    bathrooms: 1,
    squareFootage: 390,
    rentPerMonth: 1900,
    depositAmount: 1900,
    utilitiesIncluded: true,
    availableFrom: "2025-08-15",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Clara Ruiz",
    contactEmail: "clara.ruiz@email.com",
    contactPhone: "510-555-0302",
    listedAt: "2025-06-02",
    updatedAt: "2025-06-02",
    postedBy: "agent",
  },
  {
    id: 33,
    campus: "UC Berkeley",
    address: "2600 Dwight Way",
    city: "Berkeley",
    state: "CA",
    zipCode: "94704",
    distanceToCampus: 0.7,
    type: "house",
    bedrooms: 4,
    bathrooms: 2,
    squareFootage: 1650,
    rentPerMonth: 5200,
    depositAmount: 5200,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Paul Greene",
    contactEmail: "paul.greene@email.com",
    contactPhone: "510-555-0303",
    listedAt: "2025-06-03",
    updatedAt: "2025-06-03",
    postedBy: "agent",
  },
  {
    id: 34,
    campus: "UC Berkeley",
    address: "2200 Channing Way",
    city: "Berkeley",
    state: "CA",
    zipCode: "94704",
    distanceToCampus: 0.4,
    type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 580,
    rentPerMonth: 2100,
    depositAmount: 2100,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Iris Yamamoto",
    contactEmail: "iris.yamamoto@email.com",
    contactPhone: "510-555-0304",
    listedAt: "2025-06-04",
    updatedAt: "2025-06-04",
    postedBy: "agent",
  },
  {
    id: 35,
    campus: "UC Berkeley",
    address: "1700 Shattuck Ave",
    city: "Berkeley",
    state: "CA",
    zipCode: "94709",
    distanceToCampus: 1.0,
    type: "condo",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1020,
    rentPerMonth: 3600,
    depositAmount: 3600,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Victor Santos",
    contactEmail: "victor.santos@email.com",
    contactPhone: "510-555-0305",
    listedAt: "2025-06-05",
    updatedAt: "2025-06-05",
    postedBy: "agent",
  },
  {
    id: 36,
    campus: "UC Berkeley",
    address: "2750 Bancroft Way",
    city: "Berkeley",
    state: "CA",
    zipCode: "94704",
    distanceToCampus: 0.2,
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 175,
    rentPerMonth: 1050,
    depositAmount: 1050,
    utilitiesIncluded: true,
    availableFrom: "2025-08-01",
    leaseDuration: 9,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Maya Okonkwo",
    contactEmail: "maya.okonkwo@email.com",
    contactPhone: "510-555-0306",
    listedAt: "2025-06-06",
    updatedAt: "2025-06-06",
    postedBy: "student",
  },
  {
    id: 37,
    campus: "UC Berkeley",
    address: "1400 University Ave",
    city: "Berkeley",
    state: "CA",
    zipCode: "94702",
    distanceToCampus: 1.4,
    type: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1150,
    rentPerMonth: 4200,
    depositAmount: 4200,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Ethan Price",
    contactEmail: "ethan.price@email.com",
    contactPhone: "510-555-0307",
    listedAt: "2025-06-07",
    updatedAt: "2025-06-07",
    postedBy: "agent",
  },
  {
    id: 38,
    campus: "UC Berkeley",
    address: "2900 College Ave",
    city: "Berkeley",
    state: "CA",
    zipCode: "94705",
    distanceToCampus: 0.8,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFootage: 820,
    rentPerMonth: 3100,
    depositAmount: 3100,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Nora Fleming",
    contactEmail: "nora.fleming@email.com",
    contactPhone: "510-555-0308",
    listedAt: "2025-06-08",
    updatedAt: "2025-06-08",
    postedBy: "agent",
  },
  {
    id: 39,
    campus: "UC Berkeley",
    address: "1950 Dana St",
    city: "Berkeley",
    state: "CA",
    zipCode: "94704",
    distanceToCampus: 0.6,
    type: "house",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1350,
    rentPerMonth: 4800,
    depositAmount: 4800,
    utilitiesIncluded: false,
    availableFrom: "2025-09-15",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Joel Carter",
    contactEmail: "joel.carter@email.com",
    contactPhone: "510-555-0309",
    listedAt: "2025-06-09",
    updatedAt: "2025-06-09",
    postedBy: "agent",
  },
  {
    id: 40,
    campus: "UC Berkeley",
    address: "2100 Fulton St",
    city: "Berkeley",
    state: "CA",
    zipCode: "94709",
    distanceToCampus: 1.2,
    type: "studio",
    bedrooms: 0,
    bathrooms: 1,
    squareFootage: 410,
    rentPerMonth: 1850,
    depositAmount: 1850,
    utilitiesIncluded: true,
    availableFrom: "2025-07-01",
    leaseDuration: 6,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Tara Nguyen",
    contactEmail: "tara.nguyen@email.com",
    contactPhone: "510-555-0310",
    listedAt: "2025-06-10",
    updatedAt: "2025-06-10",
    postedBy: "student",
  },
  {
    id: 41,
    campus: "UC Berkeley",
    address: "3100 Piedmont Ave",
    city: "Berkeley",
    state: "CA",
    zipCode: "94705",
    distanceToCampus: 1.6,
    type: "condo",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1280,
    rentPerMonth: 4600,
    depositAmount: 4600,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: false,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: true,
      pool: true,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Donna Walsh",
    contactEmail: "donna.walsh@email.com",
    contactPhone: "510-555-0311",
    listedAt: "2025-06-11",
    updatedAt: "2025-06-11",
    postedBy: "agent",
  },
  {
    id: 42,
    campus: "UC Berkeley",
    address: "2450 Parker St",
    city: "Berkeley",
    state: "CA",
    zipCode: "94704",
    distanceToCampus: 0.9,
    type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 530,
    rentPerMonth: 2000,
    depositAmount: 2000,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Chris Holloway",
    contactEmail: "chris.holloway@email.com",
    contactPhone: "510-555-0312",
    listedAt: "2025-06-12",
    updatedAt: "2025-06-12",
    postedBy: "agent",
  },
  {
    id: 43,
    campus: "UC Berkeley",
    address: "1600 Hearst Ave",
    city: "Berkeley",
    state: "CA",
    zipCode: "94709",
    distanceToCampus: 0.5,
    type: "house",
    bedrooms: 5,
    bathrooms: 3,
    squareFootage: 2100,
    rentPerMonth: 6800,
    depositAmount: 6800,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Sandra Moon",
    contactEmail: "sandra.moon@email.com",
    contactPhone: "510-555-0313",
    listedAt: "2025-06-13",
    updatedAt: "2025-06-13",
    postedBy: "agent",
  },
  {
    id: 44,
    campus: "UC Berkeley",
    address: "2300 Ellsworth St",
    city: "Berkeley",
    state: "CA",
    zipCode: "94704",
    distanceToCampus: 1.1,
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 195,
    rentPerMonth: 950,
    depositAmount: 950,
    utilitiesIncluded: true,
    availableFrom: "2025-08-01",
    leaseDuration: 9,
    amenities: {
      petsAllowed: false,
      parking: false,
      laundryInUnit: false,
      laundryInBuilding: true,
      furnished: true,
      ac: false,
      gym: false,
      pool: false,
      wheelchairAccessible: false,
    },
    images: [],
    contactName: "Felix Jordan",
    contactEmail: "felix.jordan@email.com",
    contactPhone: "510-555-0314",
    listedAt: "2025-06-14",
    updatedAt: "2025-06-14",
    postedBy: "student",
  },
  {
    id: 45,
    campus: "UC Berkeley",
    address: "1100 Spruce St",
    city: "Berkeley",
    state: "CA",
    zipCode: "94707",
    distanceToCampus: 1.8,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 960,
    rentPerMonth: 3400,
    depositAmount: 3400,
    utilitiesIncluded: false,
    availableFrom: "2025-09-01",
    leaseDuration: 12,
    amenities: {
      petsAllowed: true,
      parking: true,
      laundryInUnit: true,
      laundryInBuilding: false,
      furnished: false,
      ac: true,
      gym: false,
      pool: false,
      wheelchairAccessible: true,
    },
    images: [],
    contactName: "Olivia Stern",
    contactEmail: "olivia.stern@email.com",
    contactPhone: "510-555-0315",
    listedAt: "2025-06-15",
    updatedAt: "2025-06-15",
    postedBy: "agent",
  },
];

export function fetchById(id: number) {
  return initialListings.find((listing) => listing.id === id);
}
